resources:
  - name: app_registry
    type: cliConfig
    integration: app_registry

  - name: app_image
    type: image
    integration: app_registry
    pointer:
      sourceName: ric03uec/aarch64_app
    seed:
      versionName: master

jobs:
  - name: aarch64_blog_runCI
    type: runCI
    steps:
      - IN: app_registry
      - OUT: app_image

  - name: build_app_image
    type: runSh
    runtime:
      nodePool: aarch64_ubuntu1604
    steps:
      - IN: app_registry
        switch: off
      - IN: app_image
        switch: off
      - TASK:
          name: build_app_image
          script:
            - uname -a
            - echo "pull the image with provided tag"


################################################
################ CI Config #####################
################################################
language: node_js
node_js:
  - 8.4.0

runtime:
  nodePool: aarch64_ubuntu1604

build:
  pre_ci_boot:
    image_name: drydockaarch64/u16nodeall
    image_tag: v6.2.4
  ci:
    - node --version
    - docker --version
    - echo "run some tests here"
    - echo "use shipctl to get registry login"
    - echo "build latest master image and push"
