resources:
  - name: app_registry
    type: cliConfig
    integration: app_registry

  - name: app_image
    type: image
    integration: app_registry
    pointer:
      sourceName: ric03uec/aarch64_blog
    seed:
      versionName: master

jobs:
  - name: app_runCI
    type: runCI
    steps:
      - IN: app_registry

################################################
################ CI Config #####################
################################################
language: node_js
node_js:
  - 8.4.0

build:
  ci:
    - node --version
    - docker --version
    - echo "run some tests here"
    - echo "use shipctl to get registry login"
    - echo "build latest master image and push"
