resources:
  - name: app_registry
    type: cliConfig
    integration: app_registry

  - name: app_image
    type: image
    integration: app_registry
    pointer:
      sourceName: ric03uec/aarch64_app
    seed:
      versionName: master

jobs:
  - name: aarch64_blog_runCI
    type: runCI
    steps:
      - IN: app_registry
      - OUT: app_image

  - name: deploy_app
    type: runSh
    runtime:
      nodePool: aarch64_ubuntu1604
    steps:
      - IN: app_registry
        switch: off
      - IN: app_image
        switch: off
      - TASK:
          name: build_app_image
          script:
            - uname -a
            - echo "ssh into the machine and deploy application"

################################################
################ CI Config #####################
################################################
language: node_js
node_js:
  - 8.4.0

runtime:
  nodePool: aarch64_ubuntu1604

build:
  pre_ci_boot:
    image_name: drydockaarch64/u16nodall
    image_tag: v6.2.4
  ci:
    - export IMAGE_NAME=ric03uec/demoblog:ci.$BUILD_NUMBER
    - node --version
    - docker --version
    - env
    - echo "run some tests here"
    - echo "use shipctl to get registry login"
    - echo "build latest master image and push"
    #- docker build -t $IMAGE_NAME -f Dockerfile .
    #- docker push $IMAGE_NAME
  on_success:
    - echo "Saving the job version as image tag"
    #- echo versionName=$IMAGE_NAME > "$JOB_STATE/$IMAGE_BLOG_NAME.env"
